[package]
name = "aravis-port-net"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "UDP discovery and GVCP transaction handling for aravis-port"

[dependencies]
aravis-port-core.workspace = true
log.workspace = true

[dev-dependencies]
env_logger.workspace = true
