[workspace]
resolver = "2"
members = [
    "aravis-port-core",
    "aravis-port-genicam",
    "aravis-port-device",
    "aravis-port-stream",
    "aravis-port",
    "aravis-port-fakecamera",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
repository = "https://github.com/javerik/aravis-port"
readme = "README.md"
keywords = ["gigevision", "genicam", "machine-vision", "camera"]
categories = ["hardware-support", "network-programming", "computer-vision"]

[workspace.dependencies]
aravis-port-core = { path = "aravis-port-core", version = "0.2.0" }
aravis-port-genicam = { path = "aravis-port-genicam", version = "0.2.0" }
aravis-port-device = { path = "aravis-port-device", version = "0.2.0" }
aravis-port-stream = { path = "aravis-port-stream", version = "0.2.0" }
aravis-port-fakecamera = { path = "aravis-port-fakecamera", version = "0.2.0" }
quick-xml = "0.36"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
rand = "0.10"
crc32fast = "1.4"
bitflags = "2.6"

[profile.release]
opt-level = 3
