[workspace]
resolver = "2"
members = [
    "aravis-port-core",
    "aravis-port-net",
    "aravis-port-genicam",
    "aravis-port-memory",
    "aravis-port-device",
    "aravis-port-stream",
    "aravis-port",
    "aravis-port-fakecamera",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aravis-project/aravis-port"

[workspace.dependencies]
aravis-port-core = { path = "aravis-port-core" }
aravis-port-net = { path = "aravis-port-net" }
aravis-port-genicam = { path = "aravis-port-genicam" }
aravis-port-memory = { path = "aravis-port-memory" }
aravis-port-device = { path = "aravis-port-device" }
aravis-port-stream = { path = "aravis-port-stream" }
aravis-port-fakecamera = { path = "aravis-port-fakecamera" }
quick-xml = "0.36"
thiserror = "1.0"
log = "0.4"
env_logger = "0.11"
rand = "0.8"
crc32fast = "1.4"
bitflags = "2.6"

[profile.release]
opt-level = 3
